In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDRegressor # For linear regression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics # For evaluation metrics

In [2]:
df = pd.read_csv('advertising.csv')
print(df.head())

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9


In [3]:
#multiple linear regression

X = df[['TV','Radio','Newspaper']] #giving multiple features so we use double brackets
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 80% training and 20% test
print(X_train)



        TV  Radio  Newspaper
79   116.0    7.7       23.1
197  177.0    9.3        6.4
38    43.1   26.7       35.1
24    62.3   12.6       18.3
122  224.0    2.4       15.6
..     ...    ...        ...
106   25.0   11.0       29.7
14   204.1   32.9       46.0
92   217.7   33.5       59.0
179  165.6   10.0       17.6
102  280.2   10.1       21.4

[160 rows x 3 columns]


In [4]:
#Scale the feature 
#Create scaler object
scaler = StandardScaler()

In [5]:
#fit the scaler on the training data and transform both training and testing data
x_train_scaled = scaler.fit_transform(X_train)
print(x_train_scaled)

#transform the test data using the same scaler
x_test_scaled = scaler.transform(X_test)

[[-4.04248386e-01 -1.02823707e+00 -3.37675384e-01]
 [ 3.20607716e-01 -9.19827737e-01 -1.16143931e+00]
 [-1.27051084e+00  2.59123702e-01  2.54250789e-01]
 [-1.04235941e+00 -6.96233499e-01 -5.74445854e-01]
 [ 8.79103401e-01 -1.38734296e+00 -7.07629243e-01]
 [-1.32873699e+00 -1.29926038e+00 -7.96418169e-01]
 [-9.43731452e-01 -4.65863678e-01  5.35415722e-01]
 [-3.23140256e-02  6.94073782e-02 -5.34984109e-01]
 [-5.39713297e-01 -1.16374872e+00  2.19721762e-01]
 [-8.75998996e-01  3.13328366e-01 -6.87898371e-01]
 [-8.53421511e-01  1.62101588e+00  2.24654481e-01]
 [ 2.18414888e-01 -1.06889056e+00 -8.45745350e-01]
 [-1.67928215e+00  1.76330312e+00  2.22240532e+00]
 [-1.68997675e+00  1.08574483e+00  1.01882210e+00]
 [-8.74810708e-01 -1.49575229e+00 -7.47090988e-01]
 [-2.45017701e-01 -1.16374872e+00  6.68075010e-02]
 [-9.10459368e-01 -3.98107848e-01 -8.40812632e-01]
 [ 1.65980907e+00  1.31611465e+00  1.04841841e+00]
 [-1.54975868e+00 -1.88064775e-01 -6.38571189e-01]
 [ 5.65395186e-01 -1.31281155e+

In [6]:
#tol=it means tolerance
#max_iter=number of iterations
sgd_model = SGDRegressor(max_iter=5000,tol=1e-4,random_state=42)
sgd_model.fit(x_train_scaled, y_train)


SGDRegressor(max_iter=5000, random_state=42, tol=0.0001)

In [7]:
print(f"Intercept (W0): {sgd_model.intercept_[0]}")
print(f"Coefficients (W1, W2, W3): {sgd_model.coef_}")


Intercept (W0): 15.330515210050452
Coefficients (W1, W2, W3): [4.58909146 1.48714655 0.08958022]


In [8]:
# Evaluate the model
y_pred = sgd_model.predict(x_test_scaled)

mse = metrics.mean_squared_error(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error: {rmse}")



Mean Squared Error: 2.910291709031081
Root Mean Squared Error: 1.705957710211798


In [9]:

# Example prediction
new_data = np.array([[17.2, 45.9, 69.3]])  # TV, Radio, Newspaper
new_data_scaled = scaler.transform(new_data)
predicted_sales = sgd_model.predict(new_data_scaled)
print(f"Predicted Sales for TV=150, Radio=25, Newspaper=20: {predicted_sales[0]}")

Predicted Sales for TV=150, Radio=25, Newspaper=20: 10.581553247215371


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
